{% set name = "VulkanSceneGraph" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vsg-dev/VulkanSceneGraph/archive/v{{ version }}.tar.gz
    sha256: 6219e0918cbfccab088b0aba9c582c46d41dbfc01cf8be7714655880ee289206
    patches:
      - patches/ignore-vulkan-version.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('vulkanscenegraph', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
    - pkgconfig  # [linux]
  host:
    - glslang
    - libvulkan-headers
    - libvulkan-loader
    - libxcb  # [linux]
    - xorg-xproto  # [linux]
  run:
    - libvulkan-headers
    - libvulkan-loader
    - libxcb  # [linux]
    - xorg-xproto  # [linux]

test:
  commands:
    - test -f $PREFIX/include/vsg/all.h  # [not win]
    - test -f $PREFIX/lib/libvsg${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/cmake/vsg/vsgConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\vsg\\all.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\vsg.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\vsg-14.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\vsg\\vsgConfig.cmake exit 1  # [win]
  downstreams:
    - vsgxchange

about:
  home: https://vsg-dev.github.io/vsg-dev.io/
  summary: Vulkan & C++17 based Scene Graph Project
  description: |
    VulkanSceneGraph (VSG), is a modern, cross platform, high performance scene
    graph library built upon Vulkan graphics/compute API. The software is
    written in C++17, and follows the CppCoreGuidelines and FOSS Best Practices.
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/vsg-dev/VulkanSceneGraph

extra:
  recipe-maintainers:
    - jeongseok-meta
